### ISSUE TITLE
Modulo de informes

### ISSUE THREAD

**Issue by aponcepita** [onesaitplatform/onesait-cloud-platform#3]
Hola, quería preguntar si tenéis algún modulo de informes actualmente en la plataforma o planificado en el Road map.

Si no lo tenéis, solicito construirlo porque es interesante para nuestros proyectos. 

Espero vuestra respuesta.

Gracias y un saludo.

**Comment by lmgracia** [comment]
Integrado en branch https://github.com/onesaitplatform/onesait-cloud-platform/tree/feature/reports-integration
