### ISSUE TITLE
Código master - Me da problemas al hacer clean install

### ISSUE THREAD

**Issue by aponcepita** [onesaitplatform/onesait-cloud-platform#5]
Me he bajado del codigo que hay en master y he visto lo siguiente:

## Versiones en el pom

El proyecto 'onesaitplatform-parent' tiene definido la version en el pom como una release, 1.0.0

<code>

    <groupId>com.minsait.onesait.platform</groupId>
	<artifactId>onesaitplatform-parent</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>

</code>

Hay un modulo y varios ejemplos que apuntan a una SNAPSHOT (1.0.0-SNAPSHOT) de este proyecto padre. Nos centramos en el modulo 'onesaitplatform-scripting-engine'. 

<code>

	<parent>
		<groupId>com.minsait.onesait.platform</groupId>
		<artifactId>onesaitplatform-parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../..</relativePath>
	</parent>
    <groupId>com.minsait.onesait.platform</groupId>
	<artifactId>onesaitplatform-scripting-engine</artifactId>
	<packaging>jar</packaging>

</code>

## Ejecucion de proyectos

Si ejecutamos:  mvn clean install -DskipTests   del proyecto 'onesaitplatform-parent' obtengo un error en el test 'OntologyControllerTest'. Este se subsana anotandolo como @Ignore (aunque no sea muy fino hacer esto)

Os paso las trazas del error sin ignorar dicho test

<code>

ory\org\apache\httpcomponents\httpcore-nio\4.4.4\httpcore-nio[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project onesaitplatform-controlpanel: There are test failures.
-[ERROR]
4[ERROR] Please refer to D:\work\onesait-cloud-platform\sources\modules\control-panel\target\surefire-reports for the individual test results.
.[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
4[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
.4[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_191\jre\bin\java" -javaagent:D:\\users\\m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.0\\org.jacoco.agent-0.8.0-runtime.jar=destfile=D:\\work\\onesait-cloud-platform\\sources\\modules\\control-panel\\target\\jacoco.exec -jar C:\Users\aponcep\AppData\Local\Temp\surefire5952297612913979775\surefirebooter5141809352430362510.jar C:\Users\aponcep\AppData\Local\Temp\surefire5952297612913979775 2019-02-13T08-54-31_447-jvmRun1 surefire709147460204419708tmp surefire_124297869443792403412tmp"
.[ERROR] Process Exit Code: 0
j[ERROR] Crashed tests:
a[ERROR] com.minsait.onesait.platform.controlpanel.controller.ontology.OntologyControllerTest
r[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
;[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_191\jre\bin\java" -javaagent:D:\\users\\m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.0\\org.jacoco.agent-0.8.0-runtime.jar=destfile=D:\\work\\onesait-cloud-platform\\sources\\modules\\control-panel\\target\\jacoco.exec -jar C:\Users\aponcep\AppData\Local\Temp\surefire5952297612913979775\surefirebooter5141809352430362510.jar C:\Users\aponcep\AppData\Local\Temp\surefire5952297612913979775 2019-02-13T08-54-31_447-jvmRun1 surefire709147460204419708tmp surefire_124297869443792403412tmp"
D[ERROR] Process Exit Code: 0
:[ERROR] Crashed tests:
\[ERROR] com.minsait.onesait.platform.controlpanel.controller.ontology.OntologyControllerTest
u[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
s[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
e[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
r[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
s[ERROR]        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
\[ERROR]        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
m2[ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
\[ERROR]        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
r[ERROR]        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
e[ERROR]        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
p[ERROR]        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
o[ERROR]        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
s[ERROR]        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
i[ERROR]        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
t[ERROR]        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
o[ERROR]        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
r[ERROR]        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
y[ERROR]        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
\[ERROR]        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
o[ERROR]        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
r[ERROR]        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
g[ERROR]        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
\[ERROR]        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
a[ERROR]        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
p[ERROR]        at java.lang.reflect.Method.invoke(Method.java:498)
a[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
c[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
h[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
e[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

</code>

**Comment by lmgracia** [comment]
Corregido.
